export const PROJECTS = [
  {
    name: 'Expenses Tracker',
    description: 'Plataforma para gestionar tus finanzas',
    img: 'expenses-tracker.png',
    website: 'https://expenses-tracker-javiermrtnez.vercel.app',
    technologies: [
      'React',
      'Vite',
      'Typescript',
      'Zustand',
      'Firebase Auth',
      'Firestore',
      'Tailwind CSS',
      'ESLint',
    ],
  },
  {
    name: 'ToDo App',
    description: 'Aplicación para organizar y administrar tus tareas',
    img: 'todo-app.png',
    website: 'https://todo-app-javiermrtnez.vercel.app',
    technologies: [
      'React',
      'Vite',
      'Typescript',
      'Redux',
      'Firebase Auth',
      'Firestore',
      'styled-components',
      'ESLint',
    ],
  },
  {
    name: 'Advice Generator',
    description: 'Generador de consejos',
    img: 'advice-generator.png',
    website: 'https://advice-generator-javiermrtnez.vercel.app',
    technologies: ['Vite', 'React', 'Javascript'],
  },
];
